[package]
authors = ["n_lesnikov"]
edition = "2018"
name = "aoc2019"
version = "0.1.0"

[dependencies]
itertools = "0.8.2"
boolinator = "2.4.0"
smallvec = "1.0.0"
num-traits = "0.2.10"
num-integer = "0.1.41"
num-bigint = "0.2.3"
lazy_static = "1.4.0"